@startuml bodegas2-er

    hide circle
    hide empty members

    Class winery {
        winery_name: String
        origin_designation: String
    }

    Class young_wine {
        wine_name: String
        alcohol_percent: Decimal
        barrel_months: Integer
        bottle_months: Integer
    }

    Class aged_wine {
        wine_name: String
        alcohol_percent: Decimal
        barrel_months: Integer
        bottle_months: Integer
    }

    Class grape {
        grape_name: String
    }

    Class harvest {
        harvest_year: Year
        quality: String
    }

    winery "1" -- "1..*" young_wine : produce >
    winery "1" -- "1..*" aged_wine  : produce >
    aged_wine *-- "0..*" harvest
    young_wine "0..*" -- "1..*" grape : elaborado_con >
    aged_wine  "0..*" -- "1..*" grape : elaborado_con >

    ' Restricciones de negocio
    Note as rn
        RN01: Nombres de bodegas, vinos y uvas son únicos
        RN02: Límites de meses para jóvenes y crianzas
        RN03: Graduación alcohólica entre 10 y 15
        RN04: Una cosecha por vino y año
        RN05: En wine_grapes solo una FK (joven o crianza)
    End Note

@enduml
