#!/bin/bash

rm -rf exports/*

# ./exporta Aficiones/MainEstatico.puml
# ./exporta Aficiones/MainDinamico.puml
# ./exporta Animales/Main.puml
# ./exporta Apartamentos/Main.puml
./exporta Bodegas/sql/diagrams.puml
./exporta Empleados/sql/diagrams.puml
# ./exporta Espectaculos/Main.puml
#./exporta Pedidos/sql/.puml
# ./exporta Proyectos/Main.puml
./exporta Usuarios/sql/diagrams.puml
# ./exporta Usuarios2/Main.puml
./exporta Grados/sql/diagrams.puml
# ./exporta Teoria/Main.puml