@startuml usuarios-er

    hide circle
    hide empty members

    Enum Genero << Enumerado >> {
        MASCULINO
        FEMENINO
        OTRO
    }

    Class Usuario << Entidad >> {
        nombre_completo: String
        genero: Genero
        edad: Integer
        email: String
    }

    ' Restricciones de negocio
    Note as rn
        RN01: Usuarios mayores de edad
        RN02: Email único por usuario
    End Note

@enduml
