  class Persona {
    nombre: String
    edad: Integer
    nacionalidad: String
  }

  class Tenista {
    ranking: Integer
  }

  class Árbitro {
    licencia: String
  }

  class Set {
    resultado: String
  }

  class Partido {
    fecha: Date
    ronda: String
    duración: Integer
  }
