  'Agregar notas
  note as Restricciones
    Restricciones:
      - RN-01: Todos los atributos son obligatorios
      - RN-02: Los usuarios (tenistas y árbitros) deben
        ser mayores de edad. 
        RN-03: Sus nombres son únicos.
      - RN-04: El ranking de un tenista debe ser un 
        número positivo menor o igual a 1000.
      - RN-05: Un tenista no puede jugar contra sí mismo.
      - RN-06: Un árbitro no puede arbitrar más de 
        tres partidos en un mismo día.
      - RN-07: La nacionalidad de una árbitro no puede
        coincidir con la de cualquiera de los tenistas
  end note