@startuml users-er

    hide circle
    hide empty members

    Enum gender << Enumerado >> {
        male
        female
        other
    }

    Class user << Entidad >> {
        full_name: String
        gender: gender
        age: Integer
        email: String
    }

    ' Restricciones de negocio
    Note as rn
        RN01: Usuarios mayores de edad
        RN02: Email unico por usuario
    End Note

@enduml
