@startuml bodegas-dc-base
    title "Bodegas: caso base"
    hide circle
    hide empty members

    class Bodega{
        nombre: String
        denominaciónOrigen: String
    }

    class Vino{
        nombre: String
        grados: Double
    }


    class Crianza{
        tiempoBarrica: Integer
        tiempoBotella: Integer
    }

    class Joven{
        tiempoBarrica: Integer
        tiempoBotella: Integer 
    }
    class Uva{
        nombre: String
    }
    class Cosecha{
        año: Year
        calidad: String 
    }

        
        Bodega "1" -- "1..*" Vino : produce >
        Vino <|--  Joven: "{completa,disjunta}"
        Vino <|-- Crianza
        Crianza *-- "1..*" Cosecha
        Vino "0..*" -- "1..*" Uva : elaboradoCon >

        
    'Agregamos notas al modelo
    Note as rn
        RN-1: Los nombres de las bodegas, 
        vinos y uvas son únicos
        RN-2: Joven: Menos de 6 meses en barrica
        Crianza: 6 y 12 meses 
        en barrica y el resto en botella
        RN-3: Draduación está entre 
        los 10 y 15 grados
        RN-4: Cada vino de crianza tiene
        como máximo una cosecha por año
    End Note
@enduml

@startuml bodegas-dc-reservas
    title "Bodegas: extensión"

    hide circle
    hide empty members
    
    class Bodega{
        nombre: String
        denominaciónOrigen: String
    }

    class Vino{
        nombre: String
        grados: Double
    }


    class Crianza{
        tiempoBarrica: Integer
        tiempoBotella: Integer
    }
    class Joven{
        tiempoBarrica: Integer
        tiempoBotella: Integer 
    }
    class Uva{
        nombre: String
    }
    class Cosecha{
        año: Year
        calidad: String 
    }

    class Reserva <<Nuevo>>{
    tiempoBarrica: Integer
    tiempoBotella: Integer
    }
    class Valoración <<Nuevo>>{
        ranking: TipoRanking
        puntuación: Integer
    }
    enum TipoRanking  <<Nuevo>>{
        PEÑÍN
        SPECTATOR
        PARKER
        GOURMETS
    }

    <style>
    .Nuevo {
        BackgroundColor Yellow
    }
    </style>

    Bodega "1" -- "1..*" Vino : produce >
    Vino <|--  Joven
    Vino <|-- Crianza
    Vino <|-- Reserva: "{completa,disjunta}"
    Crianza *-- "1..*" Cosecha
    Reserva *-- "0..*" Valoración
    Vino "0..*" -l- "1..*" Uva : compuestoDe >
    Valoración -left[hidden]- TipoRanking
'Agregamos notas al modelo
    Note as rn
        RN-1: Los nombres de las bodegas, 
        vinos y uvas son únicos
        RN-2: Joven: Menos de 6 meses en barrica
        Crianza: 6 y 12 meses 
        en barrica y el resto en botella
        RN-3: Draduación está entre 
        los 10 y 15 grados
        RN-4: Cada vino de crianza tiene
        como máximo una cosecha por año
    End Note

    Note as ra
    Requisitos adicionales:
        RA-1: Reservas: 36 meses de crianza: 
        entre 12 y 24 meses en barrica, el resto 
        en botella
        RA-2: La puntuación está entre 0 y 100. Un 
        vino no puede tener dos valoraciones 
        del mismo ranking
    end Note
@enduml
