@BASE = http://127.0.0.1:8080/api/v1

### Cada petición tiene que empezar con 3 almohadillas.
# Positivo: Crear un nuevo usuario con todos los datos correctos
# según las reglas de negocio
POST {{BASE}}/users 
Content-Type: application/json 

{
	"full_name": "Nuevo usuario",
	"gender": "MASCULINO",
	"age": 23,
	"email": "nuevo@mail.com"
}

###
# Positivo: Crear un nuevo usuario sin especificar el género.
@name=test2
POST {{BASE}}/users 
Content-Type: application/json 

{
	"full_name": "Usuario sin genero",
	"age": 54,
	"email": "singenero@mail.com"
}

###
# Negativo: Crear un nuevo usuario sin nombre.
POST {{BASE}}/users 
Content-Type: application/json 

{
	"gender": "MASCULINO",
	"age": 23,
	"email": "sinnombre@mail.com"
}

###
# Negativo: Crear un nuevo usuario sin edad.
POST {{BASE}}/users 
Content-Type: application/json 

{
	"full_name": "Usuario sin edad",
	"gender": "MASCULINO",
	"email": "sinedad@mail.com"
}

### 
# Negativo: Crear un nuevo usuario sin email.
POST {{BASE}}/users 
Content-Type: application/json 

{
	"full_name": "Usuario sin email",
	"gender": "MASCULINO",
	"age": 54
}

### 
# Negativo: Crear un nuevo usuario con el correo repetido.
POST {{BASE}}/users 
Content-Type: application/json 

{
	"full_name": "Nuevo usuario",
	"gender": "MASCULINO",
	"age": 23,
	"email": "nuevo@mail.com"
}
### 
# Negativo: Crear un nuevo usuario menor de edad.
POST {{BASE}}/users 
Content-Type: application/json 

{
	"full_name": "Usuario menor",
	"gender": "OTRO",
	"age": 12,
	"email": "menor@mail.com"
}
