/*
 * DO NOT EDIT THIS FILE, it is auto-generated. It will be updated automatically.
 * All changes done to this file will be lost upon re-running the 'silence createapi' command.
 * If you want to create new API methods, define them in a new file.
 *
 * Silence is built and maintained by the DEAL research group at the University of Seville.
 * You can find us at https://deal.us.es
 */

"use strict";

import { BASE_URL, requestOptions } from './common.js';

const user_hobby_linksAPI_auto = {

    /** Gets all entries from 'user_hobby_links' */
    getAll: async function() {
        let response = await axios.get(`${BASE_URL}/user_hobby_links`, requestOptions);
        return response.data;
    },

    /** Gets an entry from 'user_hobby_links' by its primary key */
    getById: async function(user_hobby_id) {
        let response = await axios.get(`${BASE_URL}/user_hobby_links/${user_hobby_id}`, requestOptions);
        return response.data[0];
    },

    /** Creates a new entry in 'user_hobby_links' */
    create: async function(formData) {
        let response = await axios.post(`${BASE_URL}/user_hobby_links`, formData, requestOptions);
        return response.data;
    },

    /** Updates an existing entry in 'user_hobby_links' by its primary key */
    update: async function(formData, user_hobby_id) {
        let response = await axios.put(`${BASE_URL}/user_hobby_links/${user_hobby_id}`, formData, requestOptions);
        return response.data;
    },

    /** Deletes an existing entry in 'user_hobby_links' by its primary key */
    delete: async function(user_hobby_id) {
        let response = await axios.delete(`${BASE_URL}/user_hobby_links/${user_hobby_id}`, requestOptions);
        return response.data;
    },
};

export { user_hobby_linksAPI_auto };