@startuml aficiones-est-dc

    title "Aficiones conjunto cerrado"
    
    hide circle
    hide empty members  

    Enum Género << Enumerado >>{
        Masculino
        Femenino
        Otros
    } 
    Class Usuario << Entidad >>{
        nombre: String
        género: Género
        edad: Integer
        email: String
    } 
    Class Afición {
        afición: TipoAfición
    } 
    Enum TipoAfición {
        Literatura 
        Cine
        Deporte 
        Gastronomía
    } 

    Usuario *-- "*" Afición
@enduml
